import { PCRData } from "./types";

export const DEMO_DATA: PCRData = {
  clientName: "AssuredPartners (Example)",
  preparedFor: "",
  totalPlanMembers: 12000,
  totalMembersWithAnyRx: 4000,
  membersWithOpioidRx: 400,
  identifiedMembers: 120,
  withdrawalSymptomMembers: 120,
  catastrophicRisk: 2,
  severeRisk: 11,
  highRisk: 42,
  moderateRisk: 19,
  earlyWithdrawal: 49,
  matMembers: 9,
  totalPrescribersWithOpioid: 108,
  identifiedPrescribers: 60,
  chronicOpioidPrescribers: 25,
  acuteOpioidPrescribers: 35,
  prescribersExcessiveRefills: 16,
  pharmaciesDispensingOpioids: 175,
  pharmaciesEarlyRefills: 22,
  pharmaciesHighDosage: 8,
  crossLocationRefills: 30,
  membersMultiplePrescribers: 55,
  membersOver3Refills: 28,
  wsiUniqueMembers: 180,
  wsiBreakdown: [
    { name: "AntiDepressants", count: 138 },
    { name: "Muscle Relaxants", count: 113 },
    { name: "Nausea", count: 101 },
    { name: "AntiAnxiety", count: 44 },
    { name: "AntiPsychotics", count: 21 },
    { name: "Non-Opioid Pain", count: 19 },
    { name: "Antihistamines", count: 17 },
    { name: "Alpha-2 Agonists", count: 6 },
  ],
  chronicCostFactors: 340,
  chronicConditions: [
    { name: "Depression", count: 214 },
    { name: "GI Ulcer", count: 96 },
    { name: "Asthma", count: 63 },
    { name: "Diabetes", count: 46 },
    { name: "CAD", count: 7 },
    { name: "CHF", count: 1 },
  ],
};
